### ISSUE TITLE
It breaks when I change the version

### ISSUE THREAD

**Issue by ArtemProkopenko** [debops/ansible-elasticsearch#2]
I try change var `elasticsearch_version` to  '1.4.4', but get error

```
TASK: [debops.elasticsearch | Add Elasticsearch repository] ******************* 
failed: [default] => {"failed": true, "parsed": false}
BECOME-SUCCESS-tdnzjdlfduafwwxmhmxgthfuumqwgtci
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1430934386.72-148392519554760/apt_repository", line 2524, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1430934386.72-148392519554760/apt_repository", line 436, in main
    cache.update()
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 440, in update
    raise FetchFailedException(e)
apt.cache.FetchFailedException: W:Failed to fetch http://packages.elasticsearch.org/elasticsearch/1.4.4/debian/dists/stable/main/binary-amd64/Packages  404  Not Found [IP: 54.225.133.195 80]
, E:Some index files failed to download. They have been ignored, or old ones used instead.
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 127.0.0.1 closed.
```

**Comment by drybjed** [comment]
@ArtemProkopenko It looks like this version is not available anymore. Try using `1.5.2`, this seems to be current on https://www.elastic.co/downloads/elasticsearch

But it looks like the hosting layout changed, so role might need to be updated to reflect that.

**Comment by ArtemProkopenko** [comment]
I tried and got the same result.

**Comment by drybjed** [comment]
@ArtemProkopenko A new version of `debops.elasticsearch` role was released which dropped support for Elasticsearch 1.x, therefore I'm closing this issue as not relevant anymore.
